### ISSUE TITLE
mycity Safari support 

### ISSUE THREAD

**Issue by angerhang** [datapressio/mycity#2]
mycity won't load properly in Safari. 

http://my.london.gov.uk/#lat=51.50479&lng=-0.07864&zoom=15&budget=1000&theme=travel,green,safety,schools doesn't work either but it gets loaded properly in Chrome.

I am using Safari 9.1.1 on a Mac.

**Comment by zephod** [comment]
Thanks for pointing this out and for being patient!

I traced this to a problem with our Amazon CloudFront configuration.
Specifically, we were not allowing OPTIONS requests on the
files.datapress.com resource.

The system works fine in other browsers because they make direct GET
requests. It seems that Safari makes a preflight OPTIONS request to check
the CORS headers. Ironically the CORS headers give full access but it was
unable to receive them.

Now fixed and it's working well in Safari. Cheers :-)

On 14 June 2016 at 10:39, angerhang <notifications@github.com> wrote:

> mycity won't load properly in Safari.
>
>
> http://my.london.gov.uk/#lat=51.50479&lng=-0.07864&zoom=15&budget=1000&theme=travel,green,safety,schools
> doesn't work either but it gets loaded properly in Chrome.
>
> I am using Safari 9.1.1 on a Mac.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/datapressio/mycity/issues/2>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAFrCpvP8d3qgHax1fB-pnY14Poab2bAks5qLnbkgaJpZM4I1Ir->
> .
>



-- 
Tom Rees
CEO, Founder
http://datapress.com
